/* Modelagem Básica - Entidade = Tabela */
/* Os campos são atributos */  
CLIENTE

NOME - CARACTER (30)
CPF - NUMERICO (11)
EMAIL - CARACTER (30)
TELEFONE - CARACTER (30)	
ENDEREÇO - CARACTER (100)
SEXO - CARACTER (1)

/* Processos de MOdelagem */
/* Fase 01 e Fase 02, AD Adm de dados */

MODELAGEM CONCEITUAL - 
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* Fase 03, DBA e AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* Iniciando a Modelagem Física */
/* Criando o Banco  de dados */ 
CREATE DATABASE EXEMPLO

CREATE DATABASE PROJETO;

/* Conectando-se ao Banco */
USE PROJETO;

/* Criando a Tabela de Clientes */
CREATE TABLE CLIENTE(
	NOME VARCHAR (30),
	SEXO CHAR (1),
	EMAIL VARCHAR (30),
	CPF VARCHAR (11),
	TELEFONE VARCHAR (30),	
	ENDEREÇO VARCHAR (100)	 
);

/* Verificando as Tabelas do Bnaco */ 
 SHOW TABLES;
USE EXEMPLO;
SHOW TABLES;

USE PROJETO;

/* Descobrindo como é a estrutura de uma tabela */
DESC CLIENTE; 

/* Sintaxe básica de inserção - INSERT INTO TABELA... */
INSERT INTO CLIENTE ( NOME,SEXO,EMAIL,CPF,TELEFONE,ENDEREÇO) 
VALUES ('LILIAN','F','LILIAN@MYSQL.COM',654486808,'982357485','SENADOR SOARES-TIJUCA-RIO DE JANEIRO-RJ');
INSERT INTO CLIENTE ( NOME,SEXO,EMAIL,CPF,TELEFONE,ENDEREÇO) 
VALUES ('CELIA','F','CELIA@MYSQL.COM',652418745,'987451352','RIACHUELO-CENTRO-SAO PAULO-SP');
INSERT INTO CLIENTE ( NOME,SEXO,EMAIL,CPF,TELEFONE,ENDEREÇO) 
VALUES ('ALEX','M','ALEX@MYSQL.COM',632548221,'253658746','MANOEL BANDEIRA-CECAP-MOCOCA-SP';
INSERT INTO CLIENTE ( NOME,SEXO,EMAIL,CPF,TELEFONE,ENDEREÇO) 
VALUES ('THIAGO','M','THIAGO@MYSQL.COM',452369854,'152486845','TAGUA-CENTRO-BELO HORIZONTE-MG');

/* O Comando Select - Seleção, Projeção e Junção */
SELECT NOW();
SELECT NOW() as DATA_HORA;
SELECT NOW() as DATA_HORA, 'ALEX NASCIMETO' AS ESTUDANTE;
SELECT 'AlEX NASCIMENTO';
SELECT 'BANCO DE DADOS';

/* Alias de Colunas */
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDEREÇO FROM CLIENTE;
SELECT SEXO, EMAIL, ENDEREÇO, NOME FROM CLIENTE;
SELECT SEXO, EMAIL, ENDEREÇO, NOME, NOW() AS DATA_HORA FROM CLIENTE;

/* Apenas para fins acadêmicos */
SELECT * FROM CLIENTE;

/* Tabela Errada , nunca digite nada diretamente no banco */
CREATE TABLE CLIENTE(
	NOME VARCHAR (30),
	SEXO CHAR (1),
	EMAIL VARCHAR (30),
	CPF VARCHAR (11)
	TELEFONE VARCHAR (30),	
	ENDEREÇO VARCHAR (100)	 
)

/* Filtrando Dados com WHERE e LIKE */
SELECT NOME, TELEFONE FROM CLIENTE;

/* Filtrando */
SELECT SEXO FROM CLIENTE WHERE SEXO = 'M';
SELECT SEXO FROM CLIENTE WHERE SEXO = 'F';
SELECT NOME, ENDEREÇO FROM CLIENTE WHERE SEXO = 'F';
  
/* Utilizando o operador LIKE. Usando caracter coringa % que significa QUALQUER COISA */
SELECT NOME, SEXO FROM CLIENTE WHERE ENDEREÇO LIKE '%RJ%';
SELECT NOME, SEXO FROM CLIENTE WHERE ENDEREÇO LIKE '%RJ';
SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE WHERE ENDEREÇO LIKE '%RJ%';
SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE WHERE ENDEREÇO LIKE '%RIACHUELO%';
SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE WHERE ENDEREÇO LIKE '%TIJUCA%';
SELECT NOME, SEXO, ENDEREÇO FROM CLIENTE WHERE ENDEREÇO LIKE '%CENTRO%';





                      
 




